General upgrade of AKS and all support projects
danskernesdigitalebibliotek/dpl-platform pull request #141
Opened 2022-11-02 15:40 UTC by danquah

#### What does this PR do?
The original goal of this change was to upgrade AKS, but due to some problems with the Terraform provider I ended up rebuilding the entire environment.

As I had to rebuild the entrie cluster, and as we do not have any other environements, I took the change to upgrade all support projects as well.

#### Should this be tested by the reviewer and how?
You will have to go through all the commits. I've split them up into the individual changes for easier review.

#### What are the relevant tickets?
DDFDPDEL-212

2022-11-03 13:55 UTC, achton approved these changes
Looks great from where I'm standing! 👍🏻

2022-11-03 13:55 UTC, achton commented on infrastructure/task/scripts/util.source.sh
> +  fi
Nice optimization :wink:

2022-11-03 13:55 UTC, achton commented on documentation/runbooks/upgrading-aks.md
> +# Upgrading AKS
🙏🏻

2022-11-03 13:55 UTC, achton commented on documentation/runbooks/upgrading-aks.md
> +## 1. find out which versions of kubernetes an environment can upgrade to
This heading is a bit weirdly formatted.

2022-11-03 13:56 UTC, achton requested changes
Oh wait - I forgot I found a couple of things 😂

2022-11-08 13:01 UTC, danquah commented
@achton implemented some fixes

2022-11-09 08:07 UTC, achton approved these changes
LGTM! 👍🏻

2022-11-09 09:35 UTC, merged