instructions on how to reset a moduletest site
danskernesdigitalebibliotek/dpl-platform pull request #449
Opened 2024-09-10 14:00 UTC by ITViking

#### What does this PR do?
It describes how to reset a moduletest site

#### Should this be tested by the reviewer and how?
Read it through. You can test it on canary

#### Any specific requests for how the PR should be reviewed?
read and test it 

#### What are the relevant tickets?
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-206

2024-09-12 08:36 UTC, kasperg requested changes
:+1: Nice. I have a few questions about how we do this in practice.

2024-09-20 09:36 UTC, ITViking commented on docs/runbooks/reset-moduletest.md
> +  to "main" and run the task
I've added some more information to this step

2024-09-20 09:38 UTC, ITViking commented on docs/runbooks/reset-moduletest.md
> +5. Select "Clear Drupal Caches" and run the task
fixed

2024-09-20 09:38 UTC, ITViking commented on docs/runbooks/reset-moduletest.md
> +  to "main" and run the task
also solved by new explanation for the file step

2024-09-26 14:00 UTC, kasperg approved these changes

2024-09-29 07:20 UTC, merged